services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    container_name: python-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/code
    environment:
      - ENV=local
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    container_name: nextjs-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    # command: sh -c "npm install && npm run dev"

  # (optional) DynamoDB Local
  # dynamodb-local:
  #   image: amazon/dynamodb-local
  #   container_name: dynamodb-local
  #   ports:
  #     - "8001:8000"
