version: "3.8"

services:
  # Nginxリバースプロキシ
  nginx:
    image: nginx:alpine
    container_name: e2e-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - default
    restart: unless-stopped

  # 既存のfrontendサービスを継承し、環境変数のみ上書き
  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    environment:
      # Nginxを経由するように変更
      - NEXT_PUBLIC_API_URL=http://nginx/api

  # 既存のbackendサービスを継承し、環境変数のみ追加
  backend:
    extends:
      file: docker-compose.yml
      service: backend
    environment:
      - ENV=local
      - E2E_TEST_MODE=true

  e2e-tests:
    build:
      context: ./e2e
      dockerfile: Dockerfile.e2e
    container_name: e2e-tests
    volumes:
      - ./e2e:/app
      - /app/node_modules
    ports:
      - "9324:9323"
    environment:
      # 統一ドメインを使用
      - BASE_URL=http://nginx
      - API_URL=http://nginx/api
    depends_on:
      - nginx
      - frontend
      - backend
    networks:
      - default
    command: npm run test:e2e
networks:
  default:
    driver: bridge
