FROM public.ecr.aws/lambda/python:3.11

# zipコマンドのインストール
RUN yum install -y zip

# 作業ディレクトリの設定
WORKDIR /layer

# 必要な Python パッケージをインストール
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt -t python/

# zipファイルの作成
RUN zip -r layer.zip python/